# Generated by Django 2.0 on 2019-04-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UseAsk',
            new_name='UserAsk',
        ),
    ]
